version: '3'

services:
  web:
    build: .
    command: bin/www
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: dev.127.0.0.1.nip.io
      TRUST_PROXY: uniquelocal
      LTI_KEY: $LTI_KEY
      LTI_SECRET: $LTI_SECRET
      BUZZAPI_APP_ID: $BUZZAPI_APP_ID
      BUZZAPI_PASSWORD: $BUZZAPI_PASSWORD
      CANVAS_TOKEN: $CANVAS_TOKEN
    labels:
      - "traefik.http.routers.whoami.rule=Host(`dev.127.0.0.1.nip.io`)"
      - "traefik.http.routers.whoami.tls=true"
    expose:
      - "3000"
  reverse-proxy:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/certs:/data/traefik
      - ./traefik:/etc/traefik

